---
- hosts: localhost
  connection: local

  vars_file:
    - ./Kube-Test/env.yml

  vars:
    CHART_PATH: "./charts/"

  tasks:
    - block:

        - name: Test KinD
          shell: >
            kubectl get pods --all-namespaces
          args:
            executable: /bin/bash

        - name: Test
          shell: >
            echo "hello action!"
          args:
            executable: /bin/bash

        - name: Test Input
          shell: >
            echo {{ CHART_PATH }}
          args:
            executable: /bin/bash

  environment:
    KUBECONFIG: {{ kube_config }}
