name: CI

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Kube Test Action
        uses: saintube/Kube-Test@master
        with:
          args: "--net=host"
        
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: KinD (Kubernetes in Docker) Action
      uses: engineerd/setup-kind@v0.1.0
    - name: Helm Install
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        helm init
        kubectl create serviceaccount --namespace kube-system tiller
        kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
        sleep 40s
        kubectl get pods --all-namespaces
    - name: Testing - Create Deployment
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl create clusterrolebinding tiller-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
        helm repo add stable https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
        helm repo update
        helm install stable/nginx-ingress --set controller.hostNetwork=true，rbac.create=true
        kubectl get pods --all-namespaces
