name: CI

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Kube Test Action
        uses: saintube/Kube-Test@master
        
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: KinD (Kubernetes in Docker) Action
      uses: engineerd/setup-kind@v0.1.0
    - name: Helm Install
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        helm init
        kubectl create serviceaccount --namespace kube-system tiller
        kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
        kubectl create clusterrolebinding tiller-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
        sleep 40s
        kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
        kubectl get pods --all-namespaces
        helm version
    - name: Testing - Create Deployment
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
        helm repo update
        helm install svc-cat/catalog --name catalog --namespace catalog
        kubectl get pods --all-namespaces
