name: CI

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      # Specify our GitHub Action
      - name: Kube Test Action
        uses: saintube/Kube-Test@provision-cluster
